project_id = "gtwnuflhcsdgyjbhyeeo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public"]

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323
api_port = 54324
